parameters:

services:
  blend_ez_sitemap.content:
    class: Blend\EzSitemapBundle\Services\ContentLoader
    arguments:
      - @ezpublish.api.service.location
      - @ezpublish.api.service.search
      - @ezpublish.api.service.section
    calls:
      - [setContainer, [@service_container]]
